# Generated by Django 6.0 on 2026-01-06 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cedula_nit',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
