# Generated by Django 6.0.1 on 2026-01-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_cedula_nit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_type',
            field=models.CharField(blank=True, choices=[('ladrillera', 'ladrillera'), ('constructora', 'constructora'), ('ferreteria', 'ferreteria')], max_length=20, null=True),
        ),
    ]
