# Generated by Django 6.0.1 on 2026-01-10 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateField()),
                ('estado', models.CharField(choices=[('solicitado', 'solicitado'), ('en proceso', 'en proceso'), ('en camino', 'en camino'), ('entregado', 'entregado')], max_length=30)),
                ('direccion', models.CharField(max_length=50)),
                ('cliente', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'cliente'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
