# Generated by Django 6.0.1 on 2026-01-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='estado',
            field=models.CharField(choices=[('solicitado', 'solicitado'), ('en proceso', 'en proceso'), ('en camino', 'en camino'), ('entregado', 'entregado')], default='solicitado', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='fecha_pedido',
            field=models.DateField(auto_now_add=True),
        ),
    ]
