# Generated by Django 6.0.1 on 2026-01-11 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_alter_order_estado_alter_order_fecha_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='descuento',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='iva',
            field=models.IntegerField(default=0),
        ),
    ]
