# Generated by Django 6.0.1 on 2026-01-11 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_order_descuento_order_iva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
