# Generated by Django 6.0.1 on 2026-01-11 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0004_alter_order_descuento_alter_order_iva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='descuento',
        ),
        migrations.RemoveField(
            model_name='order',
            name='iva',
        ),
    ]
