# Generated by Django 6.0.1 on 2026-02-21 19:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0005_remove_order_descuento_remove_order_iva'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fecha_venta',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='fecha_pedido',
            field=models.DateField(blank=True, null=True),
        ),
    ]
