# Generated by Django 6.0.1 on 2026-01-10 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.CharField(max_length=150)),
                ('unidad_medida', models.CharField(choices=[('gramos', 'gramos'), ('mililitros', 'mililitros')], max_length=30)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('empresa', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'empresa'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
