# Generated by Django 6.0.1 on 2026-01-11 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
