# Generated by Django 6.0.1 on 2026-01-22 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_product_descuento_product_iva'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo_prod',
            field=models.ImageField(blank=True, null=True, upload_to='perfil/'),
        ),
    ]
