# Generated by Django 6.0.1 on 2026-02-03 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_product_photo_prod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo_prod',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
