# Generated by Django 6.0.1 on 2026-01-11 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detailOrder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailorder',
            name='total',
            field=models.DecimalField(decimal_places=2, default=1, editable=False, max_digits=10),
            preserve_default=False,
        ),
    ]
